from enum import Enum

from util import V2


# setup
DEBUG_INFO: bool = True
MAX_FRAMERATE: int = 512
USE_DEFAULT_CURSOR: bool = True

# screen
SCREEN_WIDTH: int = 1920
SCREEN_HEIGHT: int = 1080

# hex model
class HexOrientation(Enum):
    FLAT = 1
    POINTY = 2
HEX_INIT_SPRITE_SIZE: int = 256
HEX_INIT_CHUNK_SIZE: int = 2
HEX_INIT_CHUNK_OVERFLOW = -1
HEX_MIN_CHUNK_SIZE: int = 2
HEX_MAX_CHUNK_SIZE: int = 16
HEX_INIT_STORE_SIZE: V2[int] = V2(128, 80)
HEX_ORIENTATION: HexOrientation = HexOrientation.POINTY
HEX_NOF_HEXES: V2[int] = V2(HEX_INIT_CHUNK_SIZE, HEX_INIT_CHUNK_SIZE) * HEX_INIT_STORE_SIZE

# hex view
DRAG_MOVE_FACTOR: float = 1.5
HEX_MIN_SIZE: int = 4
HEX_MAX_SIZE: int = HEX_INIT_SPRITE_SIZE
ZOOM_STEP_FACTOR: float = 2
ZOOM_MOVE_FACTOR: float = .5
CHUNKS_PER_FRAME: int = 1

# heightmap
CONTINENT_NOISE_FREQUENCY: V2[int] = V2(4, 2)
CONTINENT_NOISE_WEIGHT: float = 0.85
TERRAIN0_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE.scalar_floordiv(8)
TERRAIN0_NOISE_WEIGHT: float = 0.075
TERRAIN1_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE.scalar_floordiv(4)
TERRAIN1_NOISE_WEIGHT: float = 0.05
TERRAIN2_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE.scalar_floordiv(2)
TERRAIN2_NOISE_WEIGHT: float = 0.025
assert CONTINENT_NOISE_WEIGHT + TERRAIN0_NOISE_WEIGHT + TERRAIN1_NOISE_WEIGHT + TERRAIN2_NOISE_WEIGHT == 1

CONTINENT_NOISE_PEAK_FLATTENING_RESOLUTION: float = 0.1  # lower is higher resolution
CONTINENT_NOISE_SIZE_MODIF: float = 0.8  # higher is larger continents

MOUNTAIN_RANGE_NOISE_FREQUENCY: V2[int] = V2(8, 4)
MOUNTAIN0_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE.scalar_floordiv(8)
MOUNTAIN0_NOISE_WEIGHT: float = 0.5
MOUNTAIN1_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE.scalar_floordiv(4)
MOUNTAIN1_NOISE_WEIGHT: float = 0.4
MOUNTAIN2_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE.scalar_floordiv(2)
MOUNTAIN2_NOISE_WEIGHT: float = 0.1
assert MOUNTAIN0_NOISE_WEIGHT + MOUNTAIN1_NOISE_WEIGHT + MOUNTAIN2_NOISE_WEIGHT == 1

MOUNTAIN_RANGE_NOISE_WIDTH_MODIF: float = 0.8  # lower is wider ranges
MOUNTAIN_MASK_SIZE_MODIF: float = 0.51  # higher is larger mask
MOUNTAIN_MASK_STRENGTH_MODIF: float = 2.4  # higher is stronger mask

HILL0_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE.scalar_floordiv(8)
HILL0_NOISE_WEIGHT: float = 0.5
HILL1_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE.scalar_floordiv(2)
HILL1_NOISE_WEIGHT: float = 0.4
HILL2_NOISE_FREQUENCY: V2[int] = HEX_INIT_STORE_SIZE
HILL2_NOISE_WEIGHT: float = 0.1
assert HILL0_NOISE_WEIGHT + HILL1_NOISE_WEIGHT + HILL2_NOISE_WEIGHT == 1

HILL_MASK_SIZE_MODIF: float = 0.51  # higher is larger mask
HILL_MASK_STRENGTH_MODIF: float = 2.4  # higher is stronger mask

SHADING_MULT: float = 0.88
